/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

/**
 *
 * @author Lenovo
 */
public class GUI_Sales_Manager extends javax.swing.JFrame {

    SalesManager sm;
    
    public GUI_Sales_Manager(SalesManager sm) {
        initComponents();
        this.sm = sm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonItem_entry = new javax.swing.JButton();
        buttonSupplier_entry = new javax.swing.JButton();
        Sales_manager = new javax.swing.JLabel();
        buttonDaily_item_wise_sales_entry = new javax.swing.JButton();
        buttonPRPO = new javax.swing.JButton();
        buttonMy_profile = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        System_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonItem_entry.setText("Item Entry");
        buttonItem_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem_entryActionPerformed(evt);
            }
        });

        buttonSupplier_entry.setText("Supplier Entry");
        buttonSupplier_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupplier_entryActionPerformed(evt);
            }
        });

        Sales_manager.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Sales_manager.setText("Sales Manager Home Page");

        buttonDaily_item_wise_sales_entry.setText("Daily Item-wise Sales Entry");
        buttonDaily_item_wise_sales_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaily_item_wise_sales_entryActionPerformed(evt);
            }
        });

        buttonPRPO.setText("Purchase Requisition/Purchase Order");
        buttonPRPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPRPOActionPerformed(evt);
            }
        });

        buttonMy_profile.setText("My Profile");
        buttonMy_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMy_profileActionPerformed(evt);
            }
        });

        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        System_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        System_name.setText("PURCHASE ORDER MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(System_name)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sales_manager)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonDaily_item_wise_sales_entry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonSupplier_entry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonItem_entry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonPRPO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(buttonMy_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(System_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sales_manager)
                .addGap(10, 10, 10)
                .addComponent(buttonItem_entry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSupplier_entry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDaily_item_wise_sales_entry)
                .addGap(8, 8, 8)
                .addComponent(buttonPRPO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMy_profile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLogout)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonItem_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem_entryActionPerformed
        GUI_Item_Entry item = new GUI_Item_Entry(sm);
        item.show();
        this.dispose();
    }//GEN-LAST:event_buttonItem_entryActionPerformed

    private void buttonSupplier_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupplier_entryActionPerformed
        GUI_Supplier_Entry supplier = new GUI_Supplier_Entry(sm);
        supplier.show();
        this.dispose();
    }//GEN-LAST:event_buttonSupplier_entryActionPerformed

    private void buttonDaily_item_wise_sales_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaily_item_wise_sales_entryActionPerformed
        GUI_Daily_item_Entry daily = new GUI_Daily_item_Entry(sm);
        daily.show();
        this.dispose();
    }//GEN-LAST:event_buttonDaily_item_wise_sales_entryActionPerformed

    private void buttonPRPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPRPOActionPerformed
        GUI_PRPO_Entry prpo = new GUI_PRPO_Entry(sm);
        prpo.show();
        this.dispose();
    }//GEN-LAST:event_buttonPRPOActionPerformed

    private void buttonMy_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMy_profileActionPerformed
        GUI_Profile profile = new GUI_Profile(sm);
        profile.show();
        this.dispose();
    }//GEN-LAST:event_buttonMy_profileActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        GUI_Login login = new GUI_Login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Sales_Manager(new SalesManager()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sales_manager;
    private javax.swing.JLabel System_name;
    private javax.swing.JButton buttonDaily_item_wise_sales_entry;
    private javax.swing.JButton buttonItem_entry;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonMy_profile;
    private javax.swing.JButton buttonPRPO;
    private javax.swing.JButton buttonSupplier_entry;
    // End of variables declaration//GEN-END:variables
}
