/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

/**
 *
 * @author Lenovo
 */
public class GUI_Sales_Manager extends javax.swing.JFrame {

    SalesManager sm;
    public GUI_Sales_Manager() {
        initComponents();
    }
    public GUI_Sales_Manager(SalesManager sm) {
        initComponents();
        this.sm = sm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonItem_entry = new javax.swing.JButton();
        buttonSupplier_entry = new javax.swing.JButton();
        Sales_manager = new javax.swing.JLabel();
        buttonDaily_item_wise_sales_entry = new javax.swing.JButton();
        buttonPurchase_requisition = new javax.swing.JButton();
        buttonView_po = new javax.swing.JButton();
        buttonMy_profile = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        System_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonItem_entry.setText("Item Entry");
        buttonItem_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem_entryActionPerformed(evt);
            }
        });

        buttonSupplier_entry.setText("Supplier Entry ");
        buttonSupplier_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupplier_entryActionPerformed(evt);
            }
        });

        Sales_manager.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Sales_manager.setText("Sales Manager Home Page");

        buttonDaily_item_wise_sales_entry.setText("Daily Item-wise Sales Entry");
        buttonDaily_item_wise_sales_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaily_item_wise_sales_entryActionPerformed(evt);
            }
        });

        buttonPurchase_requisition.setText("Purchase Requisition");
        buttonPurchase_requisition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPurchase_requisitionActionPerformed(evt);
            }
        });

        buttonView_po.setText("View Purchase Order");
        buttonView_po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonView_poActionPerformed(evt);
            }
        });

        buttonMy_profile.setText("My Profile");
        buttonMy_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMy_profileActionPerformed(evt);
            }
        });

        buttonLogout.setText("Logout");
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        System_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        System_name.setText("PURCHASE ORDER MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSupplier_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDaily_item_wise_sales_entry))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonView_po, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPurchase_requisition, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMy_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(System_name)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Sales_manager)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonLogout)
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(System_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sales_manager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonItem_entry)
                    .addComponent(buttonPurchase_requisition))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonView_po)
                    .addComponent(buttonSupplier_entry))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDaily_item_wise_sales_entry)
                    .addComponent(buttonMy_profile))
                .addGap(34, 34, 34)
                .addComponent(buttonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonItem_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem_entryActionPerformed
        GUI_Item_Entry item = new GUI_Item_Entry();
        item.show();
    }//GEN-LAST:event_buttonItem_entryActionPerformed

    private void buttonSupplier_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSupplier_entryActionPerformed
//        GUI_Supplier_Entry supplier = new GUI_Supplier_Entry();
//        supplier.show();
    }//GEN-LAST:event_buttonSupplier_entryActionPerformed

    private void buttonDaily_item_wise_sales_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaily_item_wise_sales_entryActionPerformed
//        GUI_Daily_item_Entry daily = new GUI_Daily_item_Entry();
//        daily.show();
    }//GEN-LAST:event_buttonDaily_item_wise_sales_entryActionPerformed

    private void buttonPurchase_requisitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPurchase_requisitionActionPerformed
//        GUI_pr purchase = new GUI_pr();
//        purchase.show();
    }//GEN-LAST:event_buttonPurchase_requisitionActionPerformed

    private void buttonView_poActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonView_poActionPerformed
//        GUI_View_po po = new GUI_View_po();
//        po.show();
    }//GEN-LAST:event_buttonView_poActionPerformed

    private void buttonMy_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMy_profileActionPerformed
//       GUI_MyProfile profile = new GUI_MyProfile();
//       profile.show();
    }//GEN-LAST:event_buttonMy_profileActionPerformed

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        GUI_Login le = new GUI_Login();
        le.show();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Sales_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Sales_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sales_manager;
    private javax.swing.JLabel System_name;
    private javax.swing.JButton buttonDaily_item_wise_sales_entry;
    private javax.swing.JButton buttonItem_entry;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonMy_profile;
    private javax.swing.JButton buttonPurchase_requisition;
    private javax.swing.JButton buttonSupplier_entry;
    private javax.swing.JButton buttonView_po;
    // End of variables declaration//GEN-END:variables
}
