/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

/**
 *
 * @author Lenovo
 */
public class Sales_Manager_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Sales_Manager
     */
    public Sales_Manager_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Item_entry = new javax.swing.JButton();
        Supplier_entry = new javax.swing.JButton();
        Sales_manager = new javax.swing.JLabel();
        Daily_item_wise_sales_entry = new javax.swing.JButton();
        Purchase_requisition = new javax.swing.JButton();
        View_po = new javax.swing.JButton();
        My_profile = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        System_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Item_entry.setText("Item Entry");
        Item_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_entryActionPerformed(evt);
            }
        });

        Supplier_entry.setText("Supplier Entry ");
        Supplier_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_entryActionPerformed(evt);
            }
        });

        Sales_manager.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Sales_manager.setText("Sales Manager Home Page");

        Daily_item_wise_sales_entry.setText("Daily Item-wise Sales Entry");
        Daily_item_wise_sales_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Daily_item_wise_sales_entryActionPerformed(evt);
            }
        });

        Purchase_requisition.setText("Purchase Requisition");
        Purchase_requisition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_requisitionActionPerformed(evt);
            }
        });

        View_po.setText("View Purchase Order");
        View_po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_poActionPerformed(evt);
            }
        });

        My_profile.setText("My Profile");
        My_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                My_profileActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        System_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        System_name.setText("PURCHASE ORDER MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Supplier_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item_entry, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Daily_item_wise_sales_entry))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(View_po, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Purchase_requisition, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(My_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(System_name)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Sales_manager)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Logout)
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(System_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sales_manager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item_entry)
                    .addComponent(Purchase_requisition))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View_po)
                    .addComponent(Supplier_entry))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Daily_item_wise_sales_entry)
                    .addComponent(My_profile))
                .addGap(34, 34, 34)
                .addComponent(Logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_entryActionPerformed
        Item_Entry_GUI item = new Item_Entry_GUI();
        item.show();
        dispose();
    }//GEN-LAST:event_Item_entryActionPerformed

    private void Supplier_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_entryActionPerformed
        Supplier_Entry_GUI supplier = new Supplier_Entry_GUI();
        supplier.show();
        dispose();
    }//GEN-LAST:event_Supplier_entryActionPerformed

    private void Daily_item_wise_sales_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Daily_item_wise_sales_entryActionPerformed
        GUI_Daily_item_Entry daily = new GUI_Daily_item_Entry();
        daily.show();
        dispose();
    }//GEN-LAST:event_Daily_item_wise_sales_entryActionPerformed

    private void Purchase_requisitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_requisitionActionPerformed
        pr_GUI purchase = new pr_GUI();
        purchase.show();
        dispose();
    }//GEN-LAST:event_Purchase_requisitionActionPerformed

    private void View_poActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_poActionPerformed
        View_po_GUI po = new View_po_GUI();
        po.show();
        dispose();
    }//GEN-LAST:event_View_poActionPerformed

    private void My_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_My_profileActionPerformed
       MyProfile_GUI profile = new MyProfile_GUI();
       profile.show();
       dispose();
    }//GEN-LAST:event_My_profileActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales_Manager_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Daily_item_wise_sales_entry;
    private javax.swing.JButton Item_entry;
    private javax.swing.JButton Logout;
    private javax.swing.JButton My_profile;
    private javax.swing.JButton Purchase_requisition;
    private javax.swing.JLabel Sales_manager;
    private javax.swing.JButton Supplier_entry;
    private javax.swing.JLabel System_name;
    private javax.swing.JButton View_po;
    // End of variables declaration//GEN-END:variables
}
